# -*- coding: utf-8 -*-
"""TeleBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qk6sMp1aWMa_aZ8OgmAjIVpClzSJkjQH
"""

!pip install pytelegrambotapi

import telebot
bot = telebot.TeleBot('5040153988:AAFTx7YklmC4sHlkQK1DuBx6qgyBkk0wsjE')

import telebot
man = []
bot = telebot.TeleBot('5040153988:AAFTx7YklmC4sHlkQK1DuBx6qgyBkk0wsjE')

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(message.chat.id, 'Привет! Я бот-регистратор. Для большейй инфорамции напиши /help')

@bot.message_handler(commands=['help'])
def add_info(message):
    bot.send_message(message.chat.id, 'Для регистрации ты должен написать имя, фамилию, возраст и Telgram ник. Для старта регистрации напиши /reg')

@bot.message_handler(commands=['reg'])
def start(message):
    bot.send_message(message.chat.id, 'Как тебя зовут: Имя, Фамилия, твой возраст и Telegrem ник')

bot.polling(none_stop=True, interval=0)

